### ISSUE TITLE
add events go through even with a bad master key

### ISSUE THREAD

**Issue by tushdante** [keenlabs/KeenClient-Python#67]
This is the code I've used

``` python
from keen.client import KeenClient

client = KeenClient(
    project_id="[projectid]",
    write_key="[writekey]",
    read_key="[readkey]",
    master_key="[masterkey]"
)


client.add_event("sign_ups", {
        "username": "lloyd" ,
        "value": 1,
    })
```

It turns out that the `add_event` will go through successfully even with a bad master key. I haven't played around enough to see if the events are written to my project, but even if they're not I think we should be returning an exception for this.

**Comment by joshukeen** [comment]
Could you confirm that you provided a working write key and an incorrect master key? In the case that an incorrect master key is provided as well as a correct write key, Keen Client shouldn’t even notice that the master key is incorrect, because the more restricted write key should be used first according to the principle of least privilege ([for more on PoLP, Wikipedia says it better than I know how](http://en.wikipedia.org/wiki/Principle_of_least_privilege)).

From scanning the code, it doesn’t look like the Python SDK for Keen uses the master key at all. One could argue that we should use the master key in the case that (a) the user doesn’t provide a write key, or (b) the user provides a write key that doesn’t work, but I think that would be a separate discussion.

**Comment by tushdante** [comment]
@joshukeen I did use a valid write key with an incorrect master key, and the events went through fine. Feel free to try this on your own. I understand the PoLP, but perhaps we should make this a discussion of using a master key as a fallback in the case of an incorrect write key.

@jdunck @stroud109  any comments?

**Comment by jdunck** [comment]
It looks like the code to include master_key is fairly new:

a686784cedda33bac30986035f98b97320cfb8c4 reset Client settings before test
7176dbda9a05151da3eb94f981c3c43e035bbf07 add some more tests
7483461c82800561819156e28c1ef393d6e056dd Bumped up the version.
94d1f4effd85475f6f48fedd32b3c8698e8ecb80 add test for creating new Client instance
dcf76007dc1d12f219eb2d5d6eca10ac62a2f58e update Documentation [skip ci]
5a811b1baf4838ab3be5d1553cb68b4d2900ef86 add test for master_key
c3a6da471acadf380166fca0e9a0fc13c155740a create KeenClient instance setting master_key
2c617e6395343843d8fea4332edaf57a2a452852 add master_key to KeenClient class
afab4935fe9d736d9626e7fc5ee8ba29026291a2 add master_key to KeenApi class
9edbf53c8f872d90d99ed3887e30aefa5c557c3e define keen.master_key

I think we should talk with Dieter, assuming he's around, about why it was partially implemented (or maybe someone remembers why...).

I think it'd be good to not include master key at all if it's not needed. Inclusion of a fallback approach is bad from a security standpoint because it complicates key rotation/replacement.  If we really do want to include master key, then I agree that a fallback from write to master might be reasonable, but again, it sounds like complication for no practical purpose.

**Comment by tushdante** [comment]
Well since the docs specifically ask for a user to set their master key as an ENV variable, we already know it exists. I think that's why it would make sense to add the fallback approach. I do agree we should figure out why it was partially implemented first.

**Comment by josephwegner** [comment]
This is old enough that I'm going to go ahead and assume we will never know why it was partially implemented. If that was all the new information, I'd advocate for removing all references to the master key.

HOWEVER, we have recently added some new API features that rely on the master key. We will be adding those to the Python SDK soon, so the existing framework around master keys will be useful.

I'm going to close this issue and recreate a new one requesting that the README be updated to lower the emphasis on providing a master key. I would like to _not_ use master key as a fallback, given that that key holds the most privilege. The docs should make it clear that the master key is not required in most situations. If the user runs into a situation where they need it and don't have it, the error messages should be sufficiently informative.
